colorcollector/urls.py
from django.contrib import admin
from django.urls import path, include
	
urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('main_app.urls')),
 ]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('colors/', views.colors_index, name='index'),
  path('colors/<int:color_id>/', views.colors_detail, name='detail'),
  path('colors/create/', views.ColorCreate.as_view(), name='colors_create'),
  path('colors/<int:pk>/update/', views.ColorUpdate.as_view(), name='colors_update'),
  path('colors/<int:pk>/delete/', views.ColorDelete.as_view(), name='colors_delete'),
  path('colors/<int:color_id>/add_mixing_color', views.add_mixing_color, name='add_mixing_color'),
  path('stars/', views.StarList.as_view(), name='stars_index'),
  path('stars/<int:pk>/', views.StarDetail.as_view(), name='stars_detail'),
  path('colors/<int:color_id>/assoc_star/<int:star_id>', views.assoc_star, name='assoc_star'),
  path('colors/<int:color_id>/unassoc_star/<int:star_id>', views.unassoc_star, name='unassoc_star'),
  path('stars/create/', views.StarCreate.as_view(), name='stars_create'),
  path('stars/<int:pk>/update/', views.StarUpdate.as_view(), name='stars_update'),
  path('stars/<int:pk>/delete/', views.StarDelete.as_view(), name='stars_delete'),

]

main_app/models.py
from django.db import models
from django.urls import reverse

MIXING_COLORS = (
  ('R', 'Red'),
  ('B', 'Blue'),
  ('Y', 'Yellow'),
)

# Create your models here.
class Star(models.Model):
    review = models.TextField(default='No review yet')
    stars = models.CharField(max_length=1)

    def __str__(self):
        return self.stars

    def get_absolute_url(self):
        return reverse('stars_detail', kwargs={'pk': self.id})

class Color(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    year = models.IntegerField()
    stars = models.ManyToManyField(Star)

    def __str__(self):
        return f'{self.name} ({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs = {'color_id': self.id})


class Mixing(models.Model):
    mix = models.CharField(
        max_length=1,
            choices = MIXING_COLORS,
            default = MIXING_COLORS[0][0])

    # color_id FK
    color = models.ForeignKey(Color, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_mix_display()}"

main_app/forms.py
from django.forms import ModelForm
from .models import Mixing

class MixingForm(ModelForm):
    class Meta:
        model = Mixing
        fields = ['mix']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Color, Star
from .forms import MixingForm

# colors = [
#   {'name': 'Viva Magenta', 'description': 'bright, vivid shade of purplish-red', 'year': 2023},
#   {'name': 'Very Peri', 'description': 'warm periwinkle, a bold lavender', 'year': 2022},
#   {'name': 'Illuminating', 'description': 'bright, cheerful yellow', 'year': 2021},
#   {'name': 'Ultimate Gray', 'description': 'timeless stone gray', 'year': 2021},
#   {'name': 'Classic Blue', 'description': 'a rich, mid-tone blue', 'year': 2020},
#   {'name': 'Living Coral', 'description': 'pinkish red-orange with golden undertone', 'year': 2019},
#   {'name': 'Ultra Violet', 'description': 'enchanting purple with blue undertones', 'year': 2018},
#   {'name': 'Greenery', 'description': 'fresh and zesty yellow-green', 'year': 2017},
# ]


def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def colors_index(request):
  colors = Color.objects.all()
  return render(request, 'colors/index.html', {
    'colors': colors
  })

def colors_detail(request, color_id):
  color = Color.objects.get(id=color_id)
  stars = Star.objects.all()
  id_list = color.stars.all().values_list('id')
  stars_color_doesnt_have = Star.objects.exclude(id__in=id_list)
  mixing_form = MixingForm()
  return render(request, 'colors/detail.html', {
    'color': color, 'mixing_form': mixing_form,
    'stars': stars_color_doesnt_have

  })

class ColorCreate(CreateView):
  model = Color
  fields = ['name', 'description', 'year']

class ColorUpdate(UpdateView):
  model = Color
  fields = ['description', 'year']

class ColorDelete(DeleteView):
  model = Color
  success_url = "/colors"

def add_mixing_color(request, color_id):
  form = MixingForm(request.POST)
  if form.is_valid():
    new_mixing = form.save(commit=False)
    new_mixing.color_id = color_id
    new_mixing.save()
    
  return redirect('detail', color_id=color_id)

class StarList(ListView):
  model = Star

class StarDetail(DetailView):
  model = Star

class StarCreate(CreateView):
  model = Star
  fields = '__all__'

class StarUpdate(UpdateView):
  model = Star
  fields = ['review', 'stars']

class StarDelete(DeleteView):
  model = Star
  success_url = '/stars'

def assoc_star(request, color_id, star_id):
  Color.objects.get(id=color_id).stars.add(star_id)
  return redirect('detail', color_id=color_id)

def unassoc_star(request, color_id, star_id):
  Color.objects.get(id=cat_id).stars.remove(star_id)
  return redirect('detail', color_id=color_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Color Collector</h1>
    <hr />
    <p>Pantone chooses Color of the Year, and colors from 2010s to 2023 are found here.</p>
    <footer>All Rights Reserved, &copy; 2023 Color Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Color Collector</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left-brand-logo">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Color Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'stars_create' %}">Add Star Rating</a></li>
          <li><a href="{% url 'stars_index' %}">View All Ratings</a></li>
          <li><a href="{% url 'colors_create' %}">Add a Color</a></li>
          <li><a href="{% url 'index' %}">View Colors</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Color Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/colors/detail.html
{% extends 'base.html' %}
{% block content %}

<h1> Color Details </h1>

<div class="row">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ color.name }}</h5>
            <p class="card-text">Description: {{ color.description|linebreaks }}</p>
            <p class="card-text">Year: {{ color.year }}</p>
            <div class="card-action">
                <a href="{% url 'colors_update' color.id %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'colors_delete' color.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
     <!-- Mixing Colors, Part 4 -->
  <div class="col-md-6">
    <form action="{% url 'add_mixing_color' color.id %}" method="POST">
      {% csrf_token %}
      {{ mixing_form.as_p }}
      <button type="submit" class="btn btn-success">Add Mixing Color</button>
    </form>
    <br>
    <table class="table table-striped">
      <thead>
        <tr><th>Mixing Colors</th></tr>
      </thead>
      <tbody>
        {% for mixing in color.mixing_set.all %}
          <tr>
            <td>{{ mixing.get_mix_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
    <!-- Mixing Colors, Part 4 end -->
</div>

<!-- Part 5 below -->
<hr>
<div class="row">
  <div class="col-md-6">
    <h3>{{ color.name }}'s Star Ratings</h3>
    {% if color.stars.count %}
      {% for star in color.stars.all %}
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">
              <span class="badge bg-secondary">{{ star.stars }}</span> {{ star.review }}
            </h5>
          </div>
          <div class="card-footer">
            <form action="{% url 'unassoc_star' color.id star.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Remove Rating</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Ratings Made</h5>
    {% endif %}
  </div>

  <div class="col-md-6">
    <h3>Give Rating</h3>
      <form action="{% url 'assoc_star' color.id 0 %}" method="POST">
        {% csrf_token %}
        <select name="stars">
          {% for star in stars %}
            <option value="{{ star.id }}">{{ star.stars }} - {{ star.review }}</option>
          {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary">Give Rating</button>
      </form>
  </div>
</div>

{% endblock %}

main_app/templates/colors/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Colors List</h1>

{% for color in colors %}
<a href="{% url 'detail' color.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ color.name }}</span>
      <p>Description: {{ color.description|linebreaks }}</p>
      <p>Year: {{ color.year }}</p>
    </div>
  </div>
  </a>
{% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

    <h1 class="home-header">Home</h1>

{% endblock %}

main_app/templates/main_app/color_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Color</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' color.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/color_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
  <h1>Add Color</h1>
{% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
  
{% endblock %}

main_app/templates/main_app/star_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Rating</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'stars_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/star_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Star Rating Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ star.review }}</span>
        <p>Rating: {{ star.stars }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'stars_update' star.id %}">Edit</a>
        <a href="{% url 'stars_delete' star.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/star_form.html
{% extends 'base.html' %}
{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add New Rating</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/star_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Rating List</h1>

{% for star in star_list %}
  <a href="{% url 'stars_detail' star.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ star.review }}</span>
            <p>Rating: {{ star.stars }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/vote_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Vote</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ vote.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'votes_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/vote_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Voting Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ vote.name }}</span>
        <p>Vote: {{ vote.name }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'votes_update' vote.id %}">Edit</a>
        <a href="{% url 'votes_delete' vote.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/vote_form.html
{% extends 'base.html' %}
{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Vote</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}